from src.core.input.problem_statement import ProblemStatement
from src.core.optimization.optimizer import Optimizer
from src.core.output.optimization_result import OptimizationResult
from src.core.optimization.variational_parameters_builder import VariationalParameterBuilder
from src.core.initialization.initializer import Initializer
from src.core.quantum_code.objective_evaluator import ObjectiveEvaluator
from scipy.optimize import minimize


# TODO: Сейчас этот оптимизатор решает исключительно стандартный QAOA. Нужно будет добавить общие ограничения.
class COBYLAOptimizer(Optimizer):
    """
    COBYLA is a non-gradient optimization method from the SciPy library.

    Attributes
    ----------
    objective: ObjectiveEvaluator
        The object that contains the objective function that needs to be optimized.
    initializer: Initializer
        Initializer of initial values of variational parameters.
    parameters_builder: VariationalParameterBuilder
        An algorithm for constructing variational parameters at each step of the iterative process.
    max_iterations: int
        Maximum number of iterations of the algorithm.
    epsilon: float
        Epsilon-area stop criterion.
    """

    def __init__(
            self,
            objective: ObjectiveEvaluator,
            initializer: Initializer,
            parameters_builder: VariationalParameterBuilder,
            max_iterations: int,
            epsilon: float
    ):
        super().__init__(objective, initializer, parameters_builder, max_iterations, epsilon)

    def optimize(
            self,
            objective: ProblemStatement,
            layers: int,
        ) -> OptimizationResult:
        """
        Runs the optimization process to determine the optimal variational parameters.

        The optimization starts from the initial parameters generated by the
        configured initializer and iteratively updates them according to the
        implemented optimization strategy. The process terminates when the
        stopping criterion is satisfied or the maximum number of iterations
        is reached.

        Args:
            objective: The optimization problem to be encoded into the quantum circuit.
            layers: Number of layers in the circuit.

        Returns:
            The ``OptimizationResult`` is the result of the optimization process, including the optimized
            variational parameters, the corresponding objective function value,
            and additional optimization statistics.
        """

        measurements = []
        def objective_function(params):
            computation_result = self.objective.evaluate(self.parameters_builder.build(params), objective)
            measurements.append(computation_result)
            return computation_result.get_energy(objective)

        p = layers
        initial_params = self.initializer.initialize(p).parameters
        result = minimize(
            fun=objective_function,
            x0=initial_params,
            method="COBYLA",
            options={
                "disp": False
            }
        )
        optimization_result = OptimizationResult(
            measurements,
            self.max_iterations,
            self.parameters_builder.build(result.x)
        )
        return optimization_result
