import nevergrad as ng
import numpy as np

from src.core.optimization.optimizer import Optimizer
from src.core.output.optimization_result import OptimizationResult
from src.core.optimization.variational_parameters_builder import VariationalParameterBuilder
from src.core.initialization.initializer import Initializer
from src.core.quantum_code.objective_evaluator import ObjectiveEvaluator
from src.core.input.problem_statement import ProblemStatement


class OnePlusOneOptimizer(Optimizer):
    """
    OnePlusOne is a non-gradient optimization method from the nevergrad library.

    Attributes
    ----------
    objective: ObjectiveEvaluator
        The object that contains the objective function that needs to be optimized.
    initializer: Initializer
        Initializer of initial values of variational parameters.
    parameters_builder: VariationalParameterBuilder
        An algorithm for constructing variational parameters at each step of the iterative process.
    max_iterations: int
        Maximum number of iterations of the algorithm.
    epsilon: float
        Epsilon-area stop criterion.
    """

    def __init__(
            self,
            objective: ObjectiveEvaluator,
            initializer: Initializer,
            parameters_builder: VariationalParameterBuilder,
            max_iterations: int,
            epsilon: float
    ):
        super().__init__(objective, initializer, parameters_builder, max_iterations, epsilon)

    def optimize(
            self,
            objective: ProblemStatement,
            layers: int,
    ) -> OptimizationResult:
        """
        Runs the optimization process to determine the optimal variational parameters.

        The optimization starts from the initial parameters generated by the
        configured initializer and iteratively updates them according to the
        implemented optimization strategy. The process terminates when the
        stopping criterion is satisfied or the maximum number of iterations
        is reached.

        Args:
            objective: The optimization problem to be encoded into the quantum circuit.
            layers: Number of layers in the circuit.

        Returns:
            The ``OptimizationResult`` is the result of the optimization process, including the optimized
            variational parameters, the corresponding objective function value,
            and additional optimization statistics.
        """
        # TODO: Добавить начальную инициализацию и результирующий объект
        p = layers
        initial_params = self.initializer.initialize(p)
        instrument = ng.p.Array(
            init=initial_params.parameters
        ).set_bounds(
            [0] * (2 * p),
            [2 * np.pi] * p + [np.pi] * p
        )
        optimizer = ng.optimizers.OnePlusOne(
            parametrization=instrument,
            budget=self.max_iterations
        )
        measurements = []
        for iteration in range(self.max_iterations):
            candidate = optimizer.ask()
            measurement = self.objective.evaluate(self.parameters_builder.build(candidate.value), objective)
            measurements.append(measurement)
            energy = measurement.get_energy(objective)
            optimizer.tell(candidate, energy)
        recommendation = optimizer.provide_recommendation()
        optimization_result = OptimizationResult(
            measurements,
            self.max_iterations,
            self.parameters_builder.build(recommendation.value)
        )
        return optimization_result
