from abc import ABC, abstractmethod
from src.core.output.optimization_result import OptimizationResult
from src.core.optimization.variational_parameters_builder import VariationalParameterBuilder
from src.core.initialization.initializer import Initializer
from src.core.quantum_code.objective_evaluator import ObjectiveEvaluator


class Optimizer(ABC):
    """
    An optimizer is an algorithm that starts an iterative process of selecting variational parameters.

    Attributes
    ----------
    objective: ObjectiveEvaluator
        The object that contains the objective function that needs to be optimized.
    initializer: Initializer
        Initializer of initial values of variational parameters.
    parameters_builder: VariationalParameterBuilder
        An algorithm for constructing variational parameters at each step of the iterative process.
    max_iterations: int
        Maximum number of iterations of the algorithm.
    epsilon: float
        Epsilon-area stop criterion.
    """
    objective: ObjectiveEvaluator
    initializer: Initializer
    parameters_builder: VariationalParameterBuilder
    max_iterations: int
    epsilon: float

    def __init__(
            self,
            objective: ObjectiveEvaluator,
            initializer: Initializer,
            parameters_builder: VariationalParameterBuilder,
            max_iterations: int,
            epsilon: float
    ):
        if not isinstance(objective, ObjectiveEvaluator):
            raise TypeError("Objective must be an instance of ObjectiveEvaluator")
        if not isinstance(initializer, Initializer):
            raise TypeError("Initializer must be an instance of Initializer")
        if not isinstance(parameters_builder, VariationalParameterBuilder):
            raise TypeError("Parameters_builder must be an instance of VariationalParameterBuilder")
        if not isinstance(max_iterations, int):
            raise TypeError("max_iterations must be an integer")
        if not isinstance(epsilon, float):
            raise TypeError("epsilon must be an float")
        if max_iterations < 0:
            raise ValueError("max_iterations must be positive")
        if epsilon < 0:
            raise ValueError("epsilon must be positive")
        self.objective = objective
        self.initializer = initializer
        self.parameters_builder = parameters_builder
        self.max_iterations = max_iterations
        self.epsilon = epsilon

    @abstractmethod
    def optimize(self, *args) -> OptimizationResult:
        """
        Runs the optimization process to determine the optimal variational parameters.

        The optimization starts from the initial parameters generated by the
        configured initializer and iteratively updates them according to the
        implemented optimization strategy. The process terminates when the
        stopping criterion is satisfied or the maximum number of iterations
        is reached.

        Returns:
            The ``OptimizationResult`` is the result of the optimization process, including the optimized
            variational parameters, the corresponding objective function value,
            and additional optimization statistics.
        """
        pass
